### ISSUE TITLE
cAsINg

### ISSUE THREAD

**Issue by vinylflamingo** [jerredrogero/DelonMusk#1]
What if Elon is really EXCITED ABOUT DOGE COIN!!!! and tweets in all caps? I don't believe your code would handle this currently.

The good news is the fix is easy!

`34:     tweet = status.text.lower()`

On line 34, add .lower() to make the entire tweet lowercase. Then no worry if he types doge, DOGE, or dOgE.

fun script! thanks for sharing. and hello from Reddit :).

**Comment by jerredrogero** [comment]
Hey, good catch! Will fix it on the next push :)
